// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GraphEdge struct {
	ID    string         `json:"id"`
	From  string         `json:"from"`
	To    string         `json:"to"`
	Type  string         `json:"type"`
	Props map[string]any `json:"props,omitempty"`
}

type GraphNode struct {
	ID     string         `json:"id"`
	Labels []string       `json:"labels"`
	Props  map[string]any `json:"props,omitempty"`
}

type GraphResult struct {
	Nodes []*GraphNode `json:"nodes"`
	Edges []*GraphEdge `json:"edges"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type UpdateDeviceInput struct {
	Name       *string `json:"name,omitempty"`
	DeviceType *string `json:"deviceType,omitempty"`
	Mip        *string `json:"mip,omitempty"`
}
