package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"matrix/api/domain"
	"matrix/api/graph/model"
)

// Nodes is the resolver for the nodes field.
func (r *deviceConnectionResolver) Nodes(ctx context.Context, obj *domain.DeviceConnection) ([]*domain.Device, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// PageInfo is the resolver for the pageInfo field.
func (r *deviceConnectionResolver) PageInfo(ctx context.Context, obj *domain.DeviceConnection) (*model.PageInfo, error) {
	panic(fmt.Errorf("not implemented: PageInfo - pageInfo"))
}

// StartAddr is the resolver for the StartAddr field.
func (r *iPv4AddrResolver) StartAddr(ctx context.Context, obj *domain.IPv4Addr) (*float64, error) {
	panic(fmt.Errorf("not implemented: StartAddr - StartAddr"))
}

// EndAddr is the resolver for the EndAddr field.
func (r *iPv4AddrResolver) EndAddr(ctx context.Context, obj *domain.IPv4Addr) (*domain.UInt32, error) {
	panic(fmt.Errorf("not implemented: EndAddr - EndAddr"))
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id string) (*domain.Device, error) {
	d, err := r.repo.GetDevice(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("device query: %w", err)
	}
	return d, nil
}

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context, first *int32, after *string) (*domain.DeviceConnection, error) {
	panic(fmt.Errorf("not implemented: Devices - devices"))
}

// DeviceTopology is the resolver for the deviceTopology field.
func (r *queryResolver) DeviceTopology(ctx context.Context, id string, depth *int32) (*model.GraphResult, error) {
	panic(fmt.Errorf("not implemented: DeviceTopology - deviceTopology"))
}

// DeviceConnection returns DeviceConnectionResolver implementation.
func (r *Resolver) DeviceConnection() DeviceConnectionResolver { return &deviceConnectionResolver{r} }

// IPv4Addr returns IPv4AddrResolver implementation.
func (r *Resolver) IPv4Addr() IPv4AddrResolver { return &iPv4AddrResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type deviceConnectionResolver struct{ *Resolver }
type iPv4AddrResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
