package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

// ── Resolver 的唯一职责 ───────────────────────────────────────────────────────
//
// Resolver 不含业务逻辑，只做三件事：
//  1. GraphQL 参数解包（*int32 → int，*string → string，nil 处理默认值）
//  2. 调 Service 方法
//  3. 把 Service 返回的 domain 类型转换成 GraphQL model 类型（如有必要）
//
// 判断逻辑该写在哪里：
//   "这是数据格式转换？" → Resolver
//   "这是业务规则？"     → Service
//   "这是数据查询？"     → Repository

import (
	"context"
	"matrix/api/domain"
	"matrix/api/graph/model"
)

// ── DeviceConnection 字段 resolver ───────────────────────────────────────────
//
// 为什么 DeviceConnection 的字段需要单独 resolver，而不是直接映射？
// gqlgen.yml 里配置了这两个字段走 resolver（见 autobind 章节），
// 这样 DeviceConnection 的分页逻辑可以在 service 层组装，resolver 只负责拆包。

func (r *deviceConnectionResolver) Nodes(_ context.Context, obj *domain.DeviceConnection) ([]*domain.Device, error) {
	return obj.Nodes, nil
}

func (r *deviceConnectionResolver) PageInfo(_ context.Context, obj *domain.DeviceConnection) (*model.PageInfo, error) {
	return &model.PageInfo{
		HasNextPage: obj.HasNextPage,
		EndCursor:   obj.EndCursor,
	}, nil
}

// ── IPv4Addr 标量 resolver ────────────────────────────────────────────────────
//
// 为什么需要这两个 resolver？
// domain.IPv4Addr 里 StartAddr/EndAddr 是 uint64，
// 但 GraphQL schema 定义的是 Float 和自定义标量 UInt32。
// gqlgen 无法自动转换，所以需要手动在 resolver 里做类型映射。
// 这是唯一合理的"类型转换写在 resolver"的场景。

func (r *iPv4AddrResolver) StartAddr(_ context.Context, obj *domain.IPv4Addr) (*float64, error) {
	v := float64(obj.StartAddr)
	return &v, nil
}

func (r *iPv4AddrResolver) EndAddr(_ context.Context, obj *domain.IPv4Addr) (*domain.UInt32, error) {
	v := domain.UInt32(obj.EndAddr)
	return &v, nil
}

// ── Query resolver ────────────────────────────────────────────────────────────

// Device resolver：参数直接透传，无需转换。
func (r *queryResolver) Device(ctx context.Context, id string) (*domain.Device, error) {
	return r.deviceSvc.Get(ctx, id)
}

// Devices resolver：唯一的工作是解包 GraphQL 的可空参数并给默认值，然后调 service。
//
// 为什么默认值逻辑在 resolver 而不是 service？
// 默认值（first=20, after=""）是 GraphQL 协议层的概念（schema 里定义的），
// service 不应该知道"GraphQL 传了 nil 表示用默认值"。
func (r *queryResolver) Devices(ctx context.Context, first *int32, after *string) (*domain.DeviceConnection, error) {
	limit := 20
	if first != nil {
		limit = int(*first)
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	return r.deviceSvc.List(ctx, limit, cursor)
}

// DeviceTopology resolver：参数解包 + 调 service + 把 domain 类型转成 GraphQL model 类型。
//
// domain → model 的转换为什么在 resolver 而不是 service？
// model.GraphResult / model.GraphNode / model.GraphEdge 是 gqlgen 生成的 GraphQL 专属类型，
// service 层不应该依赖 GraphQL 包（否则 service 就和 GraphQL 耦合了）。
// 转换逻辑简单（字段搬运），放在 resolver 完全合理。
func (r *queryResolver) DeviceTopology(ctx context.Context, id string, depth *int32) (*model.GraphResult, error) {
	d := 2
	if depth != nil {
		d = int(*depth)
	}

	devices, links, err := r.deviceSvc.Topology(ctx, id, d)
	if err != nil {
		return nil, err
	}

	// domain.Device → model.GraphNode
	nodes := make([]*model.GraphNode, 0, len(devices))
	for _, dev := range devices {
		nodes = append(nodes, &model.GraphNode{
			ID:     dev.ID,
			Labels: []string{"Device"},
			Props:  map[string]any{"name": dev.Name, "type": dev.Type, "mip": dev.MIP},
		})
	}

	// domain.DeviceLink → model.GraphEdge
	edges := make([]*model.GraphEdge, 0, len(links))
	for _, link := range links {
		if link.Relation != nil {
			edges = append(edges, &model.GraphEdge{
				ID:    link.Relation.ID,
				From:  link.Relation.FromID,
				To:    link.Relation.ToID,
				Type:  link.Relation.Type,
				Props: link.Relation.Props,
			})
		}
	}

	return &model.GraphResult{Nodes: nodes, Edges: edges}, nil
}

// ── Resolver 注册（gqlgen 要求） ──────────────────────────────────────────────
//
// 新增模块时照此格式添加：
//   func (r *Resolver) Xxx() XxxResolver { return &xxxResolver{r} }
//   type xxxResolver struct{ *Resolver }

func (r *Resolver) DeviceConnection() DeviceConnectionResolver { return &deviceConnectionResolver{r} }
func (r *Resolver) IPv4Addr() IPv4AddrResolver                 { return &iPv4AddrResolver{r} }
func (r *Resolver) Query() QueryResolver                       { return &queryResolver{r} }

type deviceConnectionResolver struct{ *Resolver }
type iPv4AddrResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
