package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

// ── Resolver 的唯一职责 ───────────────────────────────────────────────────────
//
// Resolver 不含业务逻辑，只做三件事：
//  1. GraphQL 参数解包（*int32 → int，*string → string，nil 处理默认值）
//  2. 调 Service 或 DataLoader
//  3. 把 Service 返回的 domain 类型转换成 GraphQL model 类型（如有必要）
//
// 判断逻辑该写在哪里：
//   "这是数据格式转换？" → Resolver
//   "这是业务规则？"     → Service
//   "这是数据查询？"     → Repository

import (
	"context"
	"matrix/api/domain"
	"matrix/api/graph/loader"
	"matrix/api/graph/model"
)

// ── Device 字段 resolver ──────────────────────────────────────────────────────

// Connections 是 Device.connections 字段的 resolver，使用 DataLoader 批量加载。
//
// 为什么不直接调 service.Topology，而是用 DataLoader？
// 当前端查询多个设备的 connections 时：
//   query { devices { nodes { id connections { target { id } } } } }
// gqlgen 会为每个 Device 调一次这个 resolver（假设返回了 N 个设备）。
// 如果这里直接查数据库，就是 N 次查询（N+1 问题）。
// DataLoader 把同一请求内的 N 次 Load 调用收集起来，合并成一次批量查询。
func (r *deviceResolver) Connections(ctx context.Context, obj *domain.Device) ([]*domain.DeviceLink, error) {
	return loader.For(ctx).DevLinksByDeviceID.Load(ctx, loader.DeviceLinksKey{
		DeviceID: obj.ID,
		Limit:    20,
	})
}

// ── DeviceConnection 字段 resolver ───────────────────────────────────────────
//
// DeviceConnection.nodes 已由 gqlgen 自动解析（直接读 obj.Nodes），无需手写 resolver。
// DeviceConnection.pageInfo 因为需要把 domain 字段组装成 model.PageInfo，仍走 resolver。

func (r *deviceConnectionResolver) PageInfo(_ context.Context, obj *domain.DeviceConnection) (*model.PageInfo, error) {
	return &model.PageInfo{
		HasNextPage: obj.HasNextPage,
		EndCursor:   obj.EndCursor,
	}, nil
}

// ── IPv4Addr 标量 resolver ────────────────────────────────────────────────────
//
// domain.IPv4Addr 里 StartAddr/EndAddr 是 uint64，
// 但 GraphQL schema 定义的是 Float 和自定义标量 UInt32，无法自动转换，需手动映射。

func (r *iPv4AddrResolver) StartAddr(_ context.Context, obj *domain.IPv4Addr) (*float64, error) {
	v := float64(obj.StartAddr)
	return &v, nil
}

func (r *iPv4AddrResolver) EndAddr(_ context.Context, obj *domain.IPv4Addr) (*domain.UInt32, error) {
	v := domain.UInt32(obj.EndAddr)
	return &v, nil
}

// ── Query resolver ────────────────────────────────────────────────────────────

func (r *queryResolver) Device(ctx context.Context, id string) (*domain.Device, error) {
	return r.deviceSvc.Get(ctx, id)
}

// Devices resolver：唯一的工作是解包 GraphQL 的可空参数并给默认值，然后调 service。
//
// 为什么默认值逻辑在 resolver 而不是 service？
// 默认值（first=20, after=""）是 GraphQL 协议层的概念（schema 里定义的），
// service 不应该知道"GraphQL 传了 nil 表示用默认值"。
func (r *queryResolver) Devices(ctx context.Context, first *int32, after *string) (*domain.DeviceConnection, error) {
	limit := 20
	if first != nil {
		limit = int(*first)
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}
	return r.deviceSvc.List(ctx, limit, cursor)
}

// DeviceTopology resolver：参数解包 + 调 service + 把 domain 类型转成 GraphQL model 类型。
//
// domain → model 的转换为什么在 resolver 而不是 service？
// model.GraphResult 是 gqlgen 生成的 GraphQL 专属类型，service 层不应该依赖 GraphQL 包。
func (r *queryResolver) DeviceTopology(ctx context.Context, id string, depth *int32) (*model.GraphResult, error) {
	d := 2
	if depth != nil {
		d = int(*depth)
	}

	devices, links, err := r.deviceSvc.Topology(ctx, id, d)
	if err != nil {
		return nil, err
	}

	nodes := make([]*model.GraphNode, 0, len(devices))
	for _, dev := range devices {
		nodes = append(nodes, &model.GraphNode{
			ID:     dev.ID,
			Labels: []string{"Device"},
			Props:  map[string]any{"name": dev.Name, "type": dev.Type, "mip": dev.MIP},
		})
	}

	edges := make([]*model.GraphEdge, 0, len(links))
	for _, link := range links {
		if link.Relation != nil {
			edges = append(edges, &model.GraphEdge{
				ID:    link.Relation.ID,
				From:  link.Relation.FromID,
				To:    link.Relation.ToID,
				Type:  link.Relation.Type,
				Props: link.Relation.Props,
			})
		}
	}

	return &model.GraphResult{Nodes: nodes, Edges: edges}, nil
}

// ── Resolver 注册 ─────────────────────────────────────────────────────────────
//
// 新增模块时照此格式添加：
//   func (r *Resolver) Xxx() XxxResolver { return &xxxResolver{r} }
//   type xxxResolver struct{ *Resolver }

func (r *Resolver) Device() DeviceResolver               { return &deviceResolver{r} }
func (r *Resolver) DeviceConnection() DeviceConnectionResolver { return &deviceConnectionResolver{r} }
func (r *Resolver) IPv4Addr() IPv4AddrResolver           { return &iPv4AddrResolver{r} }
func (r *Resolver) Query() QueryResolver                  { return &queryResolver{r} }

type deviceResolver struct{ *Resolver }
type deviceConnectionResolver struct{ *Resolver }
type iPv4AddrResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
